# Generated by Django 3.2.18 on 2023-05-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chickens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.PositiveIntegerField(default=None, null=True)),
                ('fowl_pox_vaccine', models.BooleanField(default=False)),
                ('birthdate', models.DateField(default=models.DateField(auto_now_add=True))),
                ('is_infected', models.BooleanField(default=False)),
                ('picture', models.ImageField(null=True, upload_to='chicken_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ChickenHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_morning_bath', models.BooleanField(default=False)),
                ('is_afternoon_bath', models.BooleanField(default=False)),
                ('is_vitamin_a', models.BooleanField(default=False)),
                ('is_vitamin_d', models.BooleanField(default=False)),
                ('is_vitamin_e', models.BooleanField(default=False)),
                ('is_vitamin_k', models.BooleanField(default=False)),
                ('is_vitamin_b1', models.BooleanField(default=False)),
                ('date', models.DateField(default=models.DateField(auto_now=True))),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chickens')),
            ],
        ),
    ]
