# Generated by Django 3.2.18 on 2023-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230518_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickens',
            name='tag_number',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
