# Generated by Django 3.2.18 on 2023-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_chickens_tag_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickens',
            name='verdict',
            field=models.CharField(default='No Verdict', max_length=255),
        ),
    ]
