# Generated by Django 3.2.18 on 2023-05-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_disease_predictions_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chickens',
            name='picture',
            field=models.ImageField(null=True, upload_to='chicken_pictures'),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='verdict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disease'),
        ),
    ]
